language: python
python:
  - "2.7"
cache: pip
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libsdl-mixer1.2 libusb-1.0 python-pyaudio libsdl1.2-dev cython cython3 libudev-dev python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev python-numpy libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev portaudio19-dev nodejs build-essential
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - python setup.py install
script:
  - python setup.py test
