language: python
python:
  - "2.7"
cache: pip
before_install:
    - sudo apt-get install -y libsdl1.2-dev
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - python setup.py install
script:
  - python setup.py test
